#!/bin/bash

prev=a

while ((1))
do
	if [[ -e log.txt ]]
	then
		sleep 2
		cur=$( tail -n 1 log.txt )
		re='^[0-9]+$'
		if ! [[ $cur =~ $re  ]]
		then
			echo "Spoiler Alert!"
		else [[ $cur != $prev ]] 
			echo $cur
			prev=$cur
		fi
	fi
done
